### ISSUE TITLE
dick bomb terrorism

### ISSUE THREAD

**Issue by lev6asc-v2** [Senvr/Senvrbot#8]
while I was pissing 2 terrorists from Afghanistan exploded my dick and made my left leg spasm at 60hz
please help

**Comment by Senvr** [comment]
try turning it off and on again

**Comment by lev6asc-v2** [comment]
alright trying it

**Comment by lev6asc-v2** [comment]
instructions unclear
I stuck a 50cal up my asshole

**Comment by Senvr** [comment]
sudo shutdown -rf now
try that

**Comment by lev6asc-v2** [comment]
my bios has been overwritten with hentai, thanks for making my pc better than what I wished it to be
